---
- name: Configure Kubernetes Master Node
  hosts: [bullseye_loadbalance_0]
  become: yes

  tasks:
    - name: Check if Kubernetes master is already initialized
      stat:
        path: "{{ item }}"
      register: kubeadm_status
      loop:
        - /etc/kubernetes/manifests/kube-apiserver.yaml
        - /etc/kubernetes/manifests/kube-controller-manager.yaml
        - /etc/kubernetes/manifests/kube-scheduler.yaml
        - /etc/kubernetes/manifests/etcd.yaml
        - /var/lib/etcd

    - name: Display current status
      debug:
        var: kubeadm_status.results

    - name: Pull Kubernetes container images
      command: "sudo kubeadm config images pull --cri-socket 'unix:///var/run/cri-dockerd.sock' --kubernetes-version v1.28.1"
      register: pull_images_output
      when: kubeadm_status.results | map(attribute='stat.exists') | select('equalto', false) | list | length > 0

    - name: Display output of 'Pull Kubernetes container images'
      debug:
        var: pull_images_output.stdout_lines
      when: pull_images_output.changed

    - name: Initialize Kubernetes master node
      command: "sudo kubeadm init --cri-socket 'unix:///var/run/cri-dockerd.sock' --pod-network-cidr 10.244.0.0/16 --kubernetes-version 1.28.1 --node-name kmaster"
      register: kubeadm_init_output
      when: kubeadm_status.results | map(attribute='stat.exists') | select('equalto', false) | list | length > 0

    - name: Display output of 'Initialize Kubernetes master node'
      debug:
        var: kubeadm_init_output.stdout_lines
      when: kubeadm_init_output.cha
