---
- name: Install Cilium CLI
  hosts: all
  become: yes

  tasks:
    - name: Set Cilium CLI version and architecture
      set_fact:
        CILIUM_CLI_VERSION: "{{ lookup('url', 'https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt') }}"
        CLI_ARCH: "amd64"
      when: "ansible_architecture == 'x86_64'"

    - name: Determine architecture for ARM64
      set_fact:
        CLI_ARCH: "arm64"
      when: "ansible_architecture == 'aarch64'"

    - name: Check if Cilium CLI executable exists
      stat:
        path: "/usr/local/bin/cilium"
      register: cilium_executable

    - name: Extract and install Cilium CLI
      command: "tar xzvf /tmp/cilium-linux-{{ CLI_ARCH }}.tar.gz -C /usr/local/bin/"
      when: cilium_executable.stat.exists == false

    - name: Display install status
      debug:
        var: cilium_executable
