---
- name: Install and Configure Kubernetes
  hosts: all
  become: yes

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"

    - name: Install Kubernetes packages with lock version
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest
        allow_downgrade: yes
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"

    - name: Check if Kubernetes packages are on hold
      ansible.builtin.shell: |
        if apt-mark showhold | grep -q "kubelet"; then
          echo "kubelet is already on hold"
        else
          apt-mark hold kubelet
        fi
        if apt-mark showhold | grep -q "kubeadm"; then
          echo "kubeadm is already on hold"
        else
          apt-mark hold kubeadm
        fi
        if apt-mark showhold | grep -q "kubectl"; then
          echo "kubectl is already on hold"
        else
          apt-mark hold kubectl
        fi
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"
