---
- name: Setup Kubernetes repository and install packages
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index and install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg  # Try "gpg" package name

    - name: Create directory for Kubernetes apt repository configuration
      file:
        path: /etc/apt/sources.list.d
        state: directory

    - name: Download the Kubernetes package signing key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"

    - name: Add Kubernetes apt repository
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"

    - name: Update apt package index and install Kubernetes packages
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"

    - name: Hold Kubernetes package versions
      apt:
        name: "{{ item }}"
        state: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"

