apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.11.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: webui
          containerPort: 5601
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/kibana/config/
      volumes:
      - name: config-volume
        configMap:
          name: kibana

---
apiVersion: v1
kind: Service
metadata:
  name: logging-kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - name: webui
      port: 5601
      targetPort: 5601
      protocol: TCP
      nodePort: 30021
  selector:
    app: kibana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
data:
  kibana.yml: |
  # 
  #server.host: "0.0.0.0"
  elasticsearch.url: "http://elk-es-http:9200"
