apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zeek-daemonset
spec:
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      hostNetwork: true
      containers:
        - name: zeek
          image: sacredspirits47/zeek-custom-ss360:pv3
          securityContext:
            privileged: true
            runAsUser: 1000  # Replace with the appropriate UID for zeek
            runAsGroup: 1000  # Replace with the appropriate GID for zeek
          volumeMounts:
            - name: data-volume
              mountPath: /data/capture-files
            - name: zeek-config-volume
              mountPath: /usr/local/zeek/etc
          ports:
            - containerPort: 4777
        - name: tcpdump
          image: sacredspirits47/ss360-tcpdump
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command: ["tcpdump", "-i", "any", "-w", "/shared-data/capture.pcap"]
          volumeMounts:
            - name: data-volume
              mountPath: /shared-data
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.11.1
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
          volumeMounts:
            - name: data-volume
              mountPath: /usr/share/filebeat/logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: zeek-config-volume
          configMap:
            name: zeek-config
        - name: filebeat-config
          configMap:
            name: filebeat-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: zeek-service
spec:
  selector:
    app: zeek
  ports:
    - name: zeek-port
      port: 47777
      targetPort: 4777
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zeek-network-policy
spec:
  podSelector:
    matchLabels:
      app: zeek
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zeek-config
data:
  node.cfg: |
    [zeek]
    type=standalone
    host=localhost
    interface=eth1

  networks.cfg: |
    10.244.0.0/16 Kubernetes

  default.cfg: |
    # Add content for default.cfg if necessary

  zeekctl.cfg: |
    LogRotationInterval = 3600
    LogExpireInterval = 0
    StatsLogEnable = 1
    StatsLogExpireInterval = 0
    StatusCmdShowAll = 0
    CrashExpireInterval = 0
    SitePolicyScripts = local.zeek
    LogDir = /usr/local/zeek/logs
    SpoolDir = /usr/local/zeek/spool

  local.zeek: |
    redef Log::default_dir = "/data/log-files";
    redef Log::default_prefix = "zeek";

    @load base/protocols/conn
    @load base/frameworks/logging/writers/ascii
    @load base/protocols/http
    @load base/protocols/dns
    @load base/protocols/ssl
    @load base/protocols/ssh
    @load base/protocols/mysql
    @load base/protocols/dhcp
    @load base/protocols/ntp
    @load misc/loaded-scripts
    @load tuning/defaults
    @load misc/capture-loss
    @load packages/zeek-kafka
    @load misc/stats
    @load misc/scan
    @load misc/detect-traceroute
    @load frameworks/software/vulnerable
    @load frameworks/software/version-changes
    @load protocols/ftp/software
    @load protocols/smtp/software
    @load protocols/ssh/software
    @load protocols/http/software
    @load protocols/conn/known-hosts
    @load protocols/conn/known-services
    @load protocols/ssl/known-certs
    @load protocols/ssl/validate-certs
    @load protocols/http/detect-sqli
    @load frameworks/files/hash-all-files
    @load frameworks/files/detect-MHR
    @load policy/tuning/json-logs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - "usr/share/filebeat/logs/*"
    output.kafka:
      hosts: ["192.168.121.3:9092"]
      topic: "test002"
      required_acks: 1
      compression: gzip
