---
- name: Install and Configure Kubernetes
  hosts: all
  become: yes

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"

    - name: Install Kubernetes packages with lock version
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest
        allow_downgrade: yes
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"

    - name: Prevent Kubernetes package updates
      ansible.builtin.shell: |
        apt-mark hold kubelet kubeadm kubectl
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bullseye"
