# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANT_BOX         = "generic/ubuntu2204"
VAGRANT_BOX_VERSION = "4.2.10"
CPUS_MASTER_NODE    = 2
CPUS_WORKER_NODE    = 1
MEMORY_MASTER_NODE  = 2048
MEMORY_WORKER_NODE  = 1024

Vagrant.configure(2) do |config|

  # Kubernetes Master Server
  config.vm.define "kmaster" do |node|
    node.vm.box               = VAGRANT_BOX
    node.vm.box_version       = VAGRANT_BOX_VERSION
    node.vm.hostname          = "kmaster.example.com"
    node.vm.network "private_network", type: "dhcp", :dev => "wlp0s20f3"  
    node.vm.network "forwarded_port", guest: 80, host: 80
    node.vm.network "forwarded_port", guest: 2049, host: 2049
    node.vm.network "forwarded_port", guest: 9901, host: 9901
    node.vm.network "forwarded_port", guest: 81, host: 81
    node.vm.network "forwarded_port", guest: 9902, host: 9902
    node.vm.synced_folder ".", "/vagrant", disabled: true
    node.vm.synced_folder ".", "/home/vagrant/nfs"
    node.vm.provider :libvirt do |v|
      v.memory  = MEMORY_MASTER_NODE
      v.cpus    = CPUS_MASTER_NODE
    end

    # Add Ansible provisioner for the master node
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "nfs.yaml"
      ansible.extra_vars = {
        nfs_config: "/etc/exports",
        nfs_config_backup: "/mnt/backups"
      }
    end
  end
end

