apiVersion: v1
kind: Namespace
metadata:
  name: zeek

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-static-data
  namespace: default
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: kmaster  
    path: "/New/Kubernetes"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-nfs-static-data-claim
  namespace: zeek  
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pv-nfs-static-data
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeek-deployment
  namespace: zeek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      containers:
      - name: zeek
        image: zeek/zeek:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: zeek-config
          mountPath: /usr/local/zeek/etc/
        - name: data-volume
          mountPath: /data
        ports:
        - containerPort: 4777
      - name: busybox-shell
        image: busybox
        tty: true
        stdin: true
        command:
          - "/bin/sh"
        volumeMounts:
        - name: zeek-config
          mountPath: /usr/local/zeek/etc/
        - name: data-volume
          mountPath: /data
      volumes:
      - name: zeek-config
        configMap:
          name: zeek-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: pv-nfs-static-data-claim  

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zeek-config
  namespace: zeek
data:
  node.cfg: |
    [zeek]
    type=standalone
    host=localhost
  networks.cfg: |
    10.244.0.0/16 Kubernetes Cluster
  default.cfg: |
    # Default Zeek configuration file
  zeekctl.cfg: |
    LogRotationInterval = 3600
    LogExpireInterval = 0
    StatsLogEnable = 1
    StatsLogExpireInterval = 0
    StatusCmdShowAll = 0
    CrashExpireInterval = 0
    SitePolicyScripts = local.zeek
    LogDir = ${LOGS}
    SpoolDir = ${SPOOL}
    BrokerDBDir = ${SPOOL}/brokerstore
    CfgDir = ${ETC}

---
apiVersion: v1
kind: Service
metadata:
  name: zeek-service
  namespace: zeek
spec:
  selector:
    app: zeek
  ports:
  - name: zeek-port
    port: 4777
    targetPort: 4777
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zeek-network-policy
  namespace: zeek
spec:
  podSelector:
    matchLabels:
      app: zeek
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
