- hosts: all
  tasks:
    - name: Download source file of libreddit
      ansible.builtin.get_url:
        url: https://github.com/libreddit/libreddit/releases/download/v0.30.1/libreddit
        dest: /tmp/libreddit

    - name: Ensure libreddit symlink exists
      ansible.builtin.file:
        path: /usr/share/bin
        state: directory

    - name: Create symlink to libreddit
      ansible.builtin.file:
        src: /tmp/libreddit
        dest: /usr/share/bin/libreddit
        state: link

    - name: Ensure systemd directory exists
      ansible.builtin.file:
        path: /etc/systemd/system
        state: directory

    - name: Generate systemd service file from template
      ansible.builtin.template:
        src: libreddit.service.j2  # Jinja2 template content for systemd service
        dest: /etc/systemd/system/libreddit.service
      notify: Start libreddit service

    - name: Reload systemd after creating service file
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable libreddit service
      ansible.builtin.service:
        name: libreddit
        state: started
        enabled: yes

    
  handlers:
    - name: Start libreddit service
      ansible.builtin.service:
        name: libreddit
        state: started

