---
- name: Install and configure Docker
  hosts: all
  become: yes
  tasks:
    - name: Install CRI-Dockerd
      get_url:
        url: https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.0/cri-dockerd-v0.2.0-linux-amd64.tar.gz
        dest: /tmp/cri-dockerd.tar.gz

    - name: Extract CRI-Dockerd
      unarchive:
        src: /tmp/cri-dockerd.tar.gz
        dest: /usr/local/bin/

    - name: Move CRI-Dockerd systemd unit files
      command: sudo mv /usr/local/bin/cri-dockerd.socket /usr/local/bin/cri-dockerd.service /etc/systemd/system/

    - name: Replace /usr/bin/cri-dockerd with /usr/local/bin/cri-dockerd in systemd unit file
      replace:
        path: /etc/systemd/system/cri-docker.service
        regexp: '/usr/bin/cri-dockerd'
        replace: '/usr/local/bin/cri-dockerd'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable CRI-Dockerd systemd unit
      systemd:
        name: cri-docker.service
        enabled: yes
        state: started

    - name: Enable CRI-Dockerd systemd socket
      systemd:
        name: cri-docker.socket
        enabled: yes
        state: started
